# HTTP server port
port = 8091

# address of owlcms.  a scan of the local network 192.168.x will be done if undefined or unreachable.
owlcms = ""

# Platform identifier if more than one platform detected
platform = "A"

# Directory to store video files (can be absolyte)
videoDir = 'videos'

# Video processing options
recode = true # true = recode using libx264, false = copy streams without recompression